server:
  port: 8080
spring:
  application:
    name: platform
  datasource:
    url: jdbc:postgresql://localhost:5433/platform
    username: postgres
    password: 951628437q
  data:
    redis:
      port: 6379
      host: localhost
      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
          timeout: 3000ms
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    username: arileverlika@163.com
    password: LPxheJfU97XbcckX
    protocol: smtp
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: jakarta.mail.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

logging:
  level:
    root: info
    com.activity: debug
mybatis-plus:
  type-aliases-package: com.activity.platform.pojo
  mapper-locations: classpath:mapper/*.xml
